-- Absence module (part 2 of 3): seed categories.
-- Paste into Supabase SQL Editor and run.

insert into absence.categories (code, label_en, label_bg, deducts_from_paid, allows_half_day, requires_approval, allows_retroactive, requires_document, color_hex) values ('PAID', 'Paid leave', 'Платен отпуск', true, true, true, false, true, '#5C7A2E') on conflict (code) do update set label_en = excluded.label_en, label_bg = excluded.label_bg, deducts_from_paid = excluded.deducts_from_paid, allows_half_day = excluded.allows_half_day, requires_approval = excluded.requires_approval, allows_retroactive = excluded.allows_retroactive, requires_document = excluded.requires_document, color_hex = excluded.color_hex;

insert into absence.categories (code, label_en, label_bg, deducts_from_paid, allows_half_day, requires_approval, allows_retroactive, requires_document, color_hex) values ('UNPAID', 'Unpaid leave', 'Неплатен отпуск', false, true, true, false, true, '#6E6E62') on conflict (code) do update set label_en = excluded.label_en, label_bg = excluded.label_bg, deducts_from_paid = excluded.deducts_from_paid, allows_half_day = excluded.allows_half_day, requires_approval = excluded.requires_approval, allows_retroactive = excluded.allows_retroactive, requires_document = excluded.requires_document, color_hex = excluded.color_hex;

insert into absence.categories (code, label_en, label_bg, deducts_from_paid, allows_half_day, requires_approval, allows_retroactive, requires_document, color_hex) values ('SICK', 'Sick leave', 'Болничен', false, false, true, true, true, '#B03A1E') on conflict (code) do update set label_en = excluded.label_en, label_bg = excluded.label_bg, deducts_from_paid = excluded.deducts_from_paid, allows_half_day = excluded.allows_half_day, requires_approval = excluded.requires_approval, allows_retroactive = excluded.allows_retroactive, requires_document = excluded.requires_document, color_hex = excluded.color_hex;

insert into absence.categories (code, label_en, label_bg, deducts_from_paid, allows_half_day, requires_approval, allows_retroactive, requires_document, color_hex) values ('PARENTAL', 'Parental leave', 'Родителски отпуск', false, false, true, false, true, '#3A6B8E') on conflict (code) do update set label_en = excluded.label_en, label_bg = excluded.label_bg, deducts_from_paid = excluded.deducts_from_paid, allows_half_day = excluded.allows_half_day, requires_approval = excluded.requires_approval, allows_retroactive = excluded.allows_retroactive, requires_document = excluded.requires_document, color_hex = excluded.color_hex;

insert into absence.categories (code, label_en, label_bg, deducts_from_paid, allows_half_day, requires_approval, allows_retroactive, requires_document, color_hex) values ('WFH', 'Work from home', 'Работа от вкъщи', false, false, true, false, false, '#B07A1A') on conflict (code) do update set label_en = excluded.label_en, label_bg = excluded.label_bg, deducts_from_paid = excluded.deducts_from_paid, allows_half_day = excluded.allows_half_day, requires_approval = excluded.requires_approval, allows_retroactive = excluded.allows_retroactive, requires_document = excluded.requires_document, color_hex = excluded.color_hex;

insert into absence.categories (code, label_en, label_bg, deducts_from_paid, allows_half_day, requires_approval, allows_retroactive, requires_document, color_hex) values ('BEREAVEMENT', 'Bereavement leave', 'Отпуск при загуба', false, false, true, true, true, '#565649') on conflict (code) do update set label_en = excluded.label_en, label_bg = excluded.label_bg, deducts_from_paid = excluded.deducts_from_paid, allows_half_day = excluded.allows_half_day, requires_approval = excluded.requires_approval, allows_retroactive = excluded.allows_retroactive, requires_document = excluded.requires_document, color_hex = excluded.color_hex;
