import type { AuditAction } from "@/lib/auth/audit";

// Bulgarian labels + tone hints for audit actions, used by the viewer.
// Keep this map in sync with the AuditAction union in lib/auth/audit.ts.

type Tone = "neutral" | "success" | "warning" | "danger" | "info";

export const AUDIT_LABELS: Record<AuditAction, { label: string; tone: Tone }> = {
  "auth.invite.sent":              { label: "Изпратена покана",        tone: "info" },
  "auth.invite.resent":            { label: "Преизпратена покана",     tone: "info" },
  "auth.invite.cancelled":         { label: "Отказана покана",         tone: "neutral" },
  "auth.invite.expired":           { label: "Изтекла покана",          tone: "warning" },
  "auth.invite.redeemed":          { label: "Приета покана",           tone: "success" },
  "auth.login.success":            { label: "Успешен вход",            tone: "success" },
  "auth.login.failed":             { label: "Неуспешен вход",          tone: "danger" },
  "auth.password.reset_requested": { label: "Заявена смяна на парола", tone: "info" },
  "auth.password.reset_completed": { label: "Сменена парола",          tone: "success" },
  "auth.logout":                   { label: "Изход",                   tone: "neutral" },
  "auth.role.changed":             { label: "Промяна на роля",         tone: "warning" },
  "auth.account.deactivated":     { label: "Промяна на статус",       tone: "warning" },
  "auth.bootstrap.first_admin":   { label: "Първи администратор",     tone: "success" },
  "absence.request.submit":        { label: "Подадена заявка",         tone: "info" },
  "absence.request.approve":       { label: "Одобрена заявка",         tone: "success" },
  "absence.request.reject":        { label: "Отхвърлена заявка",       tone: "danger" },
  "absence.request.cancel":        { label: "Отказана заявка",         tone: "neutral" },
  "absence.request.cancel_requested":{ label: "Заявен отказ",           tone: "info" },
  "absence.request.cancel_approved":{ label: "Одобрен отказ",           tone: "neutral" },
  "absence.request.cancel_rejected":{ label: "Отхвърлен отказ",         tone: "warning" },
  "absence.request.admin_override":{ label: "Админ намеса (отсъствие)",tone: "warning" },
  "absence.balance.set":           { label: "Промяна на баланс",       tone: "warning" },
  "absence.calendar.edit":         { label: "Промяна на календар",     tone: "warning" },
  "absence.calendar.note.update":  { label: "Промяна на бележка (календар)", tone: "info" },
  "absence.calendar.note.delete":  { label: "Изтрита бележка (календар)",    tone: "neutral" },
  "leads.create":                  { label: "Създаден лийд",           tone: "info" },
  "leads.update":                  { label: "Редактиран лийд",         tone: "info" },
  "leads.delete":                  { label: "Изтрит лийд",             tone: "warning" },
  "leads.restore":                 { label: "Възстановен лийд",        tone: "success" },
  "leads.owner.changed":           { label: "Смяна на отговорник",     tone: "info" },
  "leads.status.changed":          { label: "Промяна на статус",       tone: "info" },
  "leads.source.changed":          { label: "Промяна на източник (лийд)", tone: "info" },
  "leads.converted":               { label: "Преобразуван лийд",       tone: "success" },
  "leads.timer.stopped":           { label: "Спрян таймер",            tone: "success" },
  "leads.timer.escalated":         { label: "Ескалиран таймер (>24ч)", tone: "danger" },
  "leads.email.received":          { label: "Получен имейл-лийд",      tone: "info" },
  "leads.email.parse_failed":      { label: "Грешка при парсване",     tone: "warning" },
  "meetings.create":               { label: "Създадена среща",         tone: "info" },
  "meetings.update":               { label: "Редактирана среща",       tone: "info" },
  "meetings.cancel":               { label: "Отменена среща",          tone: "warning" },
  "meetings.restore":              { label: "Възстановена среща",      tone: "success" },
  "meetings.happened":             { label: "Отбелязана „състояла се“",tone: "success" },
  "meetings.field.updated":        { label: "Редактирано поле (среща)",tone: "info" },
  "property.created":              { label: "Създаден имот",             tone: "info" },
  "property.updated":              { label: "Редактиран имот",           tone: "info" },
  "property.deleted":              { label: "Изтрит имот",               tone: "warning" },
  "property.status_changed":       { label: "Промяна на статус (имот)",  tone: "info" },
  "property.seed_flagged":         { label: "Флаг при миграция",         tone: "warning" },
  "property.imported":             { label: "Импорт на имоти",           tone: "info" },
  "property.seller_normalized":    { label: "Нормализиран Продавач",     tone: "info" },
  "contract.created":              { label: "Създаден договор",           tone: "info" },
  "contract.updated":              { label: "Редактиран договор",         tone: "info" },
  "contract.deleted":              { label: "Изтрит договор",             tone: "warning" },
  "contract.imported":             { label: "Импорт на договори",         tone: "info" },
  "building.created":              { label: "Създадена сграда",          tone: "info" },
  "building.updated":              { label: "Редактирана сграда",        tone: "info" },
  "building.deactivated":          { label: "Деактивирана сграда",       tone: "warning" },
  "building.deleted":              { label: "Изтрита сграда",            tone: "warning" },
  "contact.building_migrated":     { label: "Мигрирана сграда на контакт", tone: "neutral" },
  "contact.owner.changed":         { label: "Смяна на отговорник",        tone: "info" },
  "contact.field.updated":         { label: "Редактирано поле (контакт)", tone: "info" },
  "contracts.attachment.viewed":      { label: "Преглед на файл (договор)",   tone: "neutral" },
  "contracts.attachment.downloaded":  { label: "Сваляне на файл (договор)",   tone: "info" },
  "contracts.attachment.uploaded":    { label: "Качване на файл (договор)",   tone: "info" },
  "contracts.attachment.deleted":     { label: "Изтрит файл (договор)",       tone: "warning" },
  "invoices.attachment.viewed":       { label: "Преглед на файл (фактура)",   tone: "neutral" },
  "invoices.attachment.downloaded":   { label: "Сваляне на файл (фактура)",   tone: "info" },
  "invoices.uploaded":                { label: "Качена фактура",                tone: "info" },
  "invoices.parsed":                  { label: "Разпозната фактура",            tone: "info" },
  "invoices.metadata.edited":         { label: "Редактирана фактура",           tone: "info" },
  "invoices.status.changed":          { label: "Промяна на статус (фактура)",   tone: "info" },
  "invoices.deleted":                 { label: "Изтрита фактура",               tone: "warning" },
  "invoices.section.created":         { label: "Създадена секция за фактури",   tone: "info" },
  "invoices.section.updated":         { label: "Редактирана секция за фактури", tone: "info" },
  "invoices.section.deactivated":     { label: "Деактивирана секция за фактури",tone: "warning" },
  "tasks.create":                     { label: "Създадена задача",              tone: "info" },
  "tasks.update":                     { label: "Редактирана задача",            tone: "info" },
  "tasks.status_changed":             { label: "Промяна на статус (задача)",    tone: "info" },
  "tasks.owner_changed":              { label: "Смяна на отговорник (задача)",  tone: "info" },
  "tasks.field.updated":              { label: "Редактирано поле (задача)",     tone: "info" },
  "tasks.deleted":                    { label: "Изтрита задача",                tone: "warning" },
  "activity.note.created":            { label: "Публикувана бележка",           tone: "info" },
  "activity.note.edited":             { label: "Редактирана бележка",           tone: "info" },
  "activity.note.deleted":            { label: "Изтрита бележка",               tone: "neutral" },
  "renovation.created":               { label: "Създаден ремонт",               tone: "info" },
  "renovation.updated":               { label: "Редактиран ремонт",             tone: "info" },
  "renovation.deleted":               { label: "Изтрит ремонт",                 tone: "warning" },
  "renovation.field.updated":         { label: "Редактирано поле (ремонт)",     tone: "info" },
  "renovation.status_changed":        { label: "Промяна на статус (ремонт)",    tone: "info" },
  "renovation.task.created":          { label: "Създадена задача (ремонт)",     tone: "info" },
  "renovation.task.updated":          { label: "Редактирана задача (ремонт)",   tone: "info" },
  "renovation.task.status_changed":   { label: "Промяна на статус (задача)",    tone: "info" },
  "renovation.task.deleted":          { label: "Изтрита задача (ремонт)",       tone: "warning" },
  "renovation.activity.created":      { label: "Добавена дейност (ремонт)",     tone: "info" },
  "renovation.activity.updated":      { label: "Редактирана дейност (ремонт)",  tone: "info" },
  "renovation.activity.status_changed": { label: "Промяна на статус (дейност)", tone: "info" },
  "renovation.activity.deleted":      { label: "Премахната дейност (ремонт)",   tone: "warning" },
  "renovation.activity.reordered":    { label: "Преподредени дейности",         tone: "info" },
  "renovation.activity.rechained":    { label: "Пренавити дати на дейности",    tone: "info" },
  "team.created":                     { label: "Създаден екип",                 tone: "info" },
  "team.updated":                     { label: "Редактиран екип",               tone: "info" },
  "team.deleted":                     { label: "Изтрит екип",                   tone: "warning" },
  "activity_template.created":        { label: "Добавена дейност в каталога",   tone: "info" },
  "activity_template.updated":        { label: "Редактирана дейност в каталога", tone: "info" },
  "activity_template.deleted":        { label: "Изтрита дейност от каталога",   tone: "warning" },
  "activity_template.reordered":      { label: "Преподреден каталог",           tone: "info" },
};
